# Netlify Configuration - Minimal Setup

[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"
  NPM_FLAGS = "--production=false"
  NODE_OPTIONS = "--max-old-space-size=4096"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/tools"
  to = "/en/tools"
  status = 301
  
[[redirects]]
  from = "/learn"
  to = "/en/learn"
  status = 301
  
[[redirects]]
  from = "/library"
  to = "/en/library"
  status = 301
  
[[redirects]]
  from = "/videos"
  to = "/en/videos"
  status = 301
  
[[redirects]]
  from = "/about"
  to = "/en/about"
  status = 301
  
[[redirects]]
  from = "/book-resources"
  to = "/en/book-resources"
  status = 301

# Development settings
[dev]
  command = "npm run dev"
  port = 5173